### ISSUE TITLE
Family Management

### ISSUE THREAD

**Issue by manorie** [pocketmelon/backend#1]
### Models
Family
- name
- default currency
- members

Member
   - name
   - email
   - password hash
   - admin

### Tasks
- [x] Ability to create a family
- [x] Ability to add a member to family
- [x] Ability to retrieve family & member details
- [x] Ability to edit family details 
- [x] Ability to edit member details
- [x] Ability to delete member
